# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/data_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data(object):
    def setupUi(self, Data):
        Data.setObjectName("Data")
        Data.resize(1156, 647)
        self.loadfileButton = QtWidgets.QPushButton(Data)
        self.loadfileButton.setGeometry(QtCore.QRect(515, 4, 120, 30))
        self.loadfileButton.setObjectName("loadfileButton")
        self.label_filename = QtWidgets.QLabel(Data)
        self.label_filename.setGeometry(QtCore.QRect(640, 10, 580, 17))
        self.label_filename.setObjectName("label_filename")
        self.verticalLayoutWidget = QtWidgets.QWidget(Data)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1, 8, 501, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_plot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_plot.setContentsMargins(0, 0, 0, 0)
        self.layout_plot.setObjectName("layout_plot")
        self.pushButton_plotdata = QtWidgets.QPushButton(Data)
        self.pushButton_plotdata.setGeometry(QtCore.QRect(600, 60, 89, 25))
        self.pushButton_plotdata.setObjectName("pushButton_plotdata")

        self.retranslateUi(Data)
        QtCore.QMetaObject.connectSlotsByName(Data)

    def retranslateUi(self, Data):
        _translate = QtCore.QCoreApplication.translate
        Data.setWindowTitle(_translate("Data", "Form"))
        self.loadfileButton.setText(_translate("Data", "Load whatever"))
        self.label_filename.setText(_translate("Data", "filename"))
        self.pushButton_plotdata.setText(_translate("Data", "plot"))
