# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/data_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data(object):
    def setupUi(self, Data):
        Data.setObjectName("Data")
        Data.resize(627, 584)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Data.sizePolicy().hasHeightForWidth())
        Data.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Data)
        self.gridLayout.setObjectName("gridLayout")
        self.loadfileButton = QtWidgets.QPushButton(Data)
        self.loadfileButton.setMaximumSize(QtCore.QSize(110, 16777215))
        self.loadfileButton.setObjectName("loadfileButton")
        self.gridLayout.addWidget(self.loadfileButton, 0, 3, 1, 1)
        self.checkBox_errorbars = QtWidgets.QCheckBox(Data)
        self.checkBox_errorbars.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkBox_errorbars.setObjectName("checkBox_errorbars")
        self.gridLayout.addWidget(self.checkBox_errorbars, 4, 2, 1, 1)
        self.textEdit_rho_index = QtWidgets.QTextEdit(Data)
        self.textEdit_rho_index.setMaximumSize(QtCore.QSize(100, 28))
        self.textEdit_rho_index.setObjectName("textEdit_rho_index")
        self.gridLayout.addWidget(self.textEdit_rho_index, 7, 2, 1, 1)
        self.listWidget_dataobjects = QtWidgets.QListWidget(Data)
        self.listWidget_dataobjects.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_dataobjects.setObjectName("listWidget_dataobjects")
        self.gridLayout.addWidget(self.listWidget_dataobjects, 2, 3, 8, 1)
        self.pushButton_clear = QtWidgets.QPushButton(Data)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 9, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 2, 1, 1)
        self.textEdit_index = QtWidgets.QTextEdit(Data)
        self.textEdit_index.setMaximumSize(QtCore.QSize(100, 28))
        self.textEdit_index.setObjectName("textEdit_index")
        self.gridLayout.addWidget(self.textEdit_index, 6, 2, 1, 1)
        self.comboBox_plotstyle = QtWidgets.QComboBox(Data)
        self.comboBox_plotstyle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_plotstyle.setObjectName("comboBox_plotstyle")
        self.comboBox_plotstyle.addItem("")
        self.comboBox_plotstyle.addItem("")
        self.comboBox_plotstyle.addItem("")
        self.gridLayout.addWidget(self.comboBox_plotstyle, 8, 2, 1, 1)
        self.pushButton_plotdata = QtWidgets.QPushButton(Data)
        self.pushButton_plotdata.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_plotdata.setObjectName("pushButton_plotdata")
        self.gridLayout.addWidget(self.pushButton_plotdata, 3, 2, 1, 1)
        self.pushButton_plotchimerax = QtWidgets.QPushButton(Data)
        self.pushButton_plotchimerax.setObjectName("pushButton_plotchimerax")
        self.gridLayout.addWidget(self.pushButton_plotchimerax, 11, 3, 1, 1)
        self.widget = QtWidgets.QWidget(Data)
        self.widget.setMinimumSize(QtCore.QSize(300, 250))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout_plot = QtWidgets.QVBoxLayout()
        self.layout_plot.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layout_plot.setObjectName("layout_plot")
        self.gridLayout_2.addLayout(self.layout_plot, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 13, 1)
        self.comboBox_selectpdb = QtWidgets.QComboBox(Data)
        self.comboBox_selectpdb.setObjectName("comboBox_selectpdb")
        self.gridLayout.addWidget(self.comboBox_selectpdb, 10, 3, 1, 1)

        self.retranslateUi(Data)
        QtCore.QMetaObject.connectSlotsByName(Data)

    def retranslateUi(self, Data):
        _translate = QtCore.QCoreApplication.translate
        Data.setWindowTitle(_translate("Data", "Form"))
        self.loadfileButton.setText(_translate("Data", "append data"))
        self.checkBox_errorbars.setText(_translate("Data", "Errorbars"))
        self.textEdit_rho_index.setStatusTip(_translate("Data", "Put in indices to filter detectors"))
        self.textEdit_rho_index.setPlaceholderText(_translate("Data", "rho indices"))
        self.pushButton_clear.setText(_translate("Data", "Clear"))
        self.textEdit_index.setStatusTip(_translate("Data", "Put in residue indices for filtering"))
        self.textEdit_index.setPlaceholderText(_translate("Data", "Res. indices"))
        self.comboBox_plotstyle.setItemText(0, _translate("Data", "plot"))
        self.comboBox_plotstyle.setItemText(1, _translate("Data", "bar"))
        self.comboBox_plotstyle.setItemText(2, _translate("Data", "scatter"))
        self.pushButton_plotdata.setStatusTip(_translate("Data", "Add selected data from the list of sets to the plot"))
        self.pushButton_plotdata.setText(_translate("Data", "< plot"))
        self.pushButton_plotchimerax.setText(_translate("Data", "Plot in ChimeraX"))
