# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/data_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data(object):
    def setupUi(self, Data):
        Data.setObjectName("Data")
        Data.resize(475, 512)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Data.sizePolicy().hasHeightForWidth())
        Data.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Data)
        self.gridLayout.setObjectName("gridLayout")
        self.loadfileButton = QtWidgets.QPushButton(Data)
        self.loadfileButton.setMaximumSize(QtCore.QSize(110, 16777215))
        self.loadfileButton.setObjectName("loadfileButton")
        self.gridLayout.addWidget(self.loadfileButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.layout_plot = QtWidgets.QVBoxLayout()
        self.layout_plot.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layout_plot.setObjectName("layout_plot")
        self.gridLayout.addLayout(self.layout_plot, 0, 0, 5, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        self.pushButton_plotdata = QtWidgets.QPushButton(Data)
        self.pushButton_plotdata.setMaximumSize(QtCore.QSize(45, 16777215))
        self.pushButton_plotdata.setObjectName("pushButton_plotdata")
        self.gridLayout.addWidget(self.pushButton_plotdata, 2, 2, 1, 1)
        self.label_filename = QtWidgets.QLabel(Data)
        self.label_filename.setObjectName("label_filename")
        self.gridLayout.addWidget(self.label_filename, 1, 2, 1, 2)

        self.retranslateUi(Data)
        QtCore.QMetaObject.connectSlotsByName(Data)

    def retranslateUi(self, Data):
        _translate = QtCore.QCoreApplication.translate
        Data.setWindowTitle(_translate("Data", "Form"))
        self.loadfileButton.setText(_translate("Data", "Load whatever"))
        self.pushButton_plotdata.setText(_translate("Data", "plot"))
        self.label_filename.setText(_translate("Data", "filename"))
