# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/detectors_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Detectors(object):
    def setupUi(self, Detectors):
        Detectors.setObjectName("Detectors")
        Detectors.resize(838, 418)
        self.gridLayout = QtWidgets.QGridLayout(Detectors)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.spinBox_n_det = QtWidgets.QSpinBox(Detectors)
        self.spinBox_n_det.setObjectName("spinBox_n_det")
        self.gridLayout.addWidget(self.spinBox_n_det, 1, 1, 1, 1)
        self.label_n_det = QtWidgets.QLabel(Detectors)
        self.label_n_det.setObjectName("label_n_det")
        self.gridLayout.addWidget(self.label_n_det, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Detectors)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Detectors)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Detectors)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 4, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(Detectors)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Detectors)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Detectors)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(Detectors)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Detectors)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Detectors)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 8, 1, 1, 1)

        self.retranslateUi(Detectors)
        QtCore.QMetaObject.connectSlotsByName(Detectors)

    def retranslateUi(self, Detectors):
        _translate = QtCore.QCoreApplication.translate
        Detectors.setWindowTitle(_translate("Detectors", "Form"))
        self.label_n_det.setStatusTip(_translate("Detectors", "set the number of detectors"))
        self.label_n_det.setText(_translate("Detectors", "n_det:"))
        self.label_2.setText(_translate("Detectors", "target"))
        self.pushButton_2.setText(_translate("Detectors", "r_target"))
        self.pushButton.setText(_translate("Detectors", "r_no_opt"))
        self.checkBox.setText(_translate("Detectors", "NegAllow"))
        self.label.setText(_translate("Detectors", "detectors"))
        self.label_3.setText(_translate("Detectors", "Norm"))
        self.pushButton_3.setText(_translate("Detectors", "r_auto"))
