# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/detectors_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Detectors(object):
    def setupUi(self, Detectors):
        Detectors.setObjectName("Detectors")
        Detectors.resize(400, 300)
        self.label = QtWidgets.QLabel(Detectors)
        self.label.setGeometry(QtCore.QRect(0, 0, 67, 17))
        self.label.setObjectName("label")
        self.label_n_det = QtWidgets.QLabel(Detectors)
        self.label_n_det.setGeometry(QtCore.QRect(10, 40, 51, 17))
        self.label_n_det.setObjectName("label_n_det")
        self.textEdit = QtWidgets.QTextEdit(Detectors)
        self.textEdit.setGeometry(QtCore.QRect(60, 40, 104, 31))
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Detectors)
        QtCore.QMetaObject.connectSlotsByName(Detectors)

    def retranslateUi(self, Detectors):
        _translate = QtCore.QCoreApplication.translate
        Detectors.setWindowTitle(_translate("Detectors", "Form"))
        self.label.setText(_translate("Detectors", "detectors"))
        self.label_n_det.setStatusTip(_translate("Detectors", "set the number of detectors"))
        self.label_n_det.setText(_translate("Detectors", "n_det:"))
