# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/frames_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frames(object):
    def setupUi(self, Frames):
        Frames.setObjectName("Frames")
        Frames.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Frames)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Frames)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Frames)
        QtCore.QMetaObject.connectSlotsByName(Frames)

    def retranslateUi(self, Frames):
        _translate = QtCore.QCoreApplication.translate
        Frames.setWindowTitle(_translate("Frames", "Form"))
        self.label.setText(_translate("Frames", "Frames"))
