# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/frames_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frames(object):
    def setupUi(self, Frames):
        Frames.setObjectName("Frames")
        Frames.resize(686, 300)
        self.gridLayout = QtWidgets.QGridLayout(Frames)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Frames)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(Frames)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Frames)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Frames)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Frames)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)

        self.retranslateUi(Frames)
        QtCore.QMetaObject.connectSlotsByName(Frames)

    def retranslateUi(self, Frames):
        _translate = QtCore.QCoreApplication.translate
        Frames.setWindowTitle(_translate("Frames", "Form"))
        self.label.setText(_translate("Frames", "Frames"))
        self.pushButton.setText(_translate("Frames", "append >"))
        self.pushButton_2.setText(_translate("Frames", "attach?"))
