# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ired_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_iRed(object):
    def setupUi(self, iRed):
        iRed.setObjectName("iRed")
        iRed.resize(400, 300)
        self.label = QtWidgets.QLabel(iRed)
        self.label.setGeometry(QtCore.QRect(0, 0, 67, 17))
        self.label.setObjectName("label")

        self.retranslateUi(iRed)
        QtCore.QMetaObject.connectSlotsByName(iRed)

    def retranslateUi(self, iRed):
        _translate = QtCore.QCoreApplication.translate
        iRed.setWindowTitle(_translate("iRed", "Form"))
        self.label.setText(_translate("iRed", "iRed"))
