# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mdsimulation_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MDSimulation(object):
    def setupUi(self, MDSimulation):
        MDSimulation.setObjectName("MDSimulation")
        MDSimulation.resize(770, 442)
        self.gridLayout = QtWidgets.QGridLayout(MDSimulation)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton_addpdb = QtWidgets.QPushButton(MDSimulation)
        self.pushButton_addpdb.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_addpdb.setObjectName("pushButton_addpdb")
        self.gridLayout.addWidget(self.pushButton_addpdb, 4, 1, 1, 1)
        self.listWidget_pdbs = QtWidgets.QListWidget(MDSimulation)
        self.listWidget_pdbs.setMinimumSize(QtCore.QSize(400, 4))
        self.listWidget_pdbs.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidget_pdbs.setObjectName("listWidget_pdbs")
        self.gridLayout.addWidget(self.listWidget_pdbs, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(MDSimulation)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listWidget_xtcs = QtWidgets.QListWidget(MDSimulation)
        self.listWidget_xtcs.setMinimumSize(QtCore.QSize(500, 4))
        self.listWidget_xtcs.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidget_xtcs.setObjectName("listWidget_xtcs")
        self.gridLayout.addWidget(self.listWidget_xtcs, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(MDSimulation)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.pushButton_addxtc = QtWidgets.QPushButton(MDSimulation)
        self.pushButton_addxtc.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_addxtc.setObjectName("pushButton_addxtc")
        self.gridLayout.addWidget(self.pushButton_addxtc, 0, 1, 1, 1)
        self.pushButton_loadsim = QtWidgets.QPushButton(MDSimulation)
        self.pushButton_loadsim.setObjectName("pushButton_loadsim")
        self.gridLayout.addWidget(self.pushButton_loadsim, 6, 0, 1, 2)

        self.retranslateUi(MDSimulation)
        QtCore.QMetaObject.connectSlotsByName(MDSimulation)

    def retranslateUi(self, MDSimulation):
        _translate = QtCore.QCoreApplication.translate
        MDSimulation.setWindowTitle(_translate("MDSimulation", "Form"))
        self.pushButton_addpdb.setText(_translate("MDSimulation", "+"))
        self.label.setText(_translate("MDSimulation", "Available Simulations:"))
        self.label_2.setText(_translate("MDSimulation", "Available PDB\'s:"))
        self.pushButton_addxtc.setText(_translate("MDSimulation", "+"))
        self.pushButton_loadsim.setText(_translate("MDSimulation", "Load Simulation"))
