# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mdsimulation_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MDSimulation(object):
    def setupUi(self, MDSimulation):
        MDSimulation.setObjectName("MDSimulation")
        MDSimulation.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(MDSimulation)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(MDSimulation)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(MDSimulation)
        QtCore.QMetaObject.connectSlotsByName(MDSimulation)

    def retranslateUi(self, MDSimulation):
        _translate = QtCore.QCoreApplication.translate
        MDSimulation.setWindowTitle(_translate("MDSimulation", "Form"))
        self.label.setText(_translate("MDSimulation", "TextLabel"))
