# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/selection_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selection(object):
    def setupUi(self, Selection):
        Selection.setObjectName("Selection")
        Selection.resize(400, 300)
        self.label = QtWidgets.QLabel(Selection)
        self.label.setGeometry(QtCore.QRect(90, 80, 67, 17))
        self.label.setObjectName("label")

        self.retranslateUi(Selection)
        QtCore.QMetaObject.connectSlotsByName(Selection)

    def retranslateUi(self, Selection):
        _translate = QtCore.QCoreApplication.translate
        Selection.setWindowTitle(_translate("Selection", "Form"))
        self.label.setText(_translate("Selection", "Selection"))
