# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/selection_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selection(object):
    def setupUi(self, Selection):
        Selection.setObjectName("Selection")
        Selection.resize(707, 420)
        self.pushButton_loadpdb = QtWidgets.QPushButton(Selection)
        self.pushButton_loadpdb.setGeometry(QtCore.QRect(0, 10, 89, 25))
        self.pushButton_loadpdb.setObjectName("pushButton_loadpdb")
        self.label_pdbpath = QtWidgets.QLabel(Selection)
        self.label_pdbpath.setGeometry(QtCore.QRect(91, 10, 410, 25))
        self.label_pdbpath.setObjectName("label_pdbpath")

        self.retranslateUi(Selection)
        QtCore.QMetaObject.connectSlotsByName(Selection)

    def retranslateUi(self, Selection):
        _translate = QtCore.QCoreApplication.translate
        Selection.setWindowTitle(_translate("Selection", "Form"))
        self.pushButton_loadpdb.setText(_translate("Selection", "Load .pdb"))
        self.label_pdbpath.setText(_translate("Selection", "..."))
