# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/sensitivity_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sensitivity(object):
    def setupUi(self, Sensitivity):
        Sensitivity.setObjectName("Sensitivity")
        Sensitivity.resize(506, 265)
        self.gridLayout_3 = QtWidgets.QGridLayout(Sensitivity)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout_plot = QtWidgets.QVBoxLayout()
        self.layout_plot.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.layout_plot.setContentsMargins(100, 0, -1, -1)
        self.layout_plot.setObjectName("layout_plot")
        self.gridLayout_2.addLayout(self.layout_plot, 0, 0, 4, 1)
        self.label = QtWidgets.QLabel(Sensitivity)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.pushButton_newExperiment = QtWidgets.QPushButton(Sensitivity)
        self.pushButton_newExperiment.setObjectName("pushButton_newExperiment")
        self.gridLayout_2.addWidget(self.pushButton_newExperiment, 1, 2, 1, 1)
        self.comboBox_nuctype = QtWidgets.QComboBox(Sensitivity)
        self.comboBox_nuctype.setObjectName("comboBox_nuctype")
        self.gridLayout_2.addWidget(self.comboBox_nuctype, 1, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit_vd = QtWidgets.QPlainTextEdit(Sensitivity)
        self.plainTextEdit_vd.setMinimumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vd.setMaximumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vd.setObjectName("plainTextEdit_vd")
        self.gridLayout.addWidget(self.plainTextEdit_vd, 1, 0, 1, 1)
        self.plainTextEdit_vi = QtWidgets.QPlainTextEdit(Sensitivity)
        self.plainTextEdit_vi.setMinimumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vi.setMaximumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vi.setObjectName("plainTextEdit_vi")
        self.gridLayout.addWidget(self.plainTextEdit_vi, 1, 1, 1, 1)
        self.label_vd = QtWidgets.QLabel(Sensitivity)
        self.label_vd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vd.setObjectName("label_vd")
        self.gridLayout.addWidget(self.label_vd, 0, 0, 1, 1)
        self.label_vi = QtWidgets.QLabel(Sensitivity)
        self.label_vi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vi.setObjectName("label_vi")
        self.gridLayout.addWidget(self.label_vi, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.checkBox_normalize = QtWidgets.QCheckBox(Sensitivity)
        self.checkBox_normalize.setObjectName("checkBox_normalize")
        self.gridLayout_2.addWidget(self.checkBox_normalize, 1, 1, 1, 1)
        self.comboBox_exp_no = QtWidgets.QComboBox(Sensitivity)
        self.comboBox_exp_no.setObjectName("comboBox_exp_no")
        self.gridLayout_2.addWidget(self.comboBox_exp_no, 0, 1, 1, 1)
        self.comboBox_sel_dataset = QtWidgets.QComboBox(Sensitivity)
        self.comboBox_sel_dataset.setObjectName("comboBox_sel_dataset")
        self.gridLayout_2.addWidget(self.comboBox_sel_dataset, 0, 2, 1, 1)
        self.plainTextEdit_index = QtWidgets.QPlainTextEdit(Sensitivity)
        self.plainTextEdit_index.setToolTip("")
        self.plainTextEdit_index.setObjectName("plainTextEdit_index")
        self.gridLayout_2.addWidget(self.plainTextEdit_index, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Sensitivity)
        QtCore.QMetaObject.connectSlotsByName(Sensitivity)

    def retranslateUi(self, Sensitivity):
        _translate = QtCore.QCoreApplication.translate
        Sensitivity.setWindowTitle(_translate("Sensitivity", "Form"))
        self.label.setText(_translate("Sensitivity", "Nuc. type"))
        self.pushButton_newExperiment.setStatusTip(_translate("Sensitivity", "Add a new experiment"))
        self.pushButton_newExperiment.setText(_translate("Sensitivity", "New Exp."))
        self.label_vd.setText(_translate("Sensitivity", "vd"))
        self.label_vi.setText(_translate("Sensitivity", "vi"))
        self.checkBox_normalize.setStatusTip(_translate("Sensitivity", "Normalize sensitivities"))
        self.checkBox_normalize.setText(_translate("Sensitivity", "Normalize"))
        self.comboBox_exp_no.setStatusTip(_translate("Sensitivity", "select experiment with number ..."))
        self.comboBox_sel_dataset.setStatusTip(_translate("Sensitivity", "Select sensitivity dataset"))
        self.plainTextEdit_index.setStatusTip(_translate("Sensitivity", "select indices for sensitivity (e.g. \"4\", \"3-8\" ...)"))
        self.plainTextEdit_index.setPlaceholderText(_translate("Sensitivity", "Indices"))
