# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/sensitivity_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sensitivity(object):
    def setupUi(self, Sensitivity):
        Sensitivity.setObjectName("Sensitivity")
        Sensitivity.resize(797, 543)
        self.verticalLayoutWidget = QtWidgets.QWidget(Sensitivity)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 2, 401, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_plot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_plot.setContentsMargins(0, 0, 0, 0)
        self.layout_plot.setObjectName("layout_plot")
        self.checkBox_normalize = QtWidgets.QCheckBox(Sensitivity)
        self.checkBox_normalize.setGeometry(QtCore.QRect(10, 240, 92, 23))
        self.checkBox_normalize.setObjectName("checkBox_normalize")
        self.comboBox_sel_dataset = QtWidgets.QComboBox(Sensitivity)
        self.comboBox_sel_dataset.setGeometry(QtCore.QRect(10, 320, 131, 25))
        self.comboBox_sel_dataset.setObjectName("comboBox_sel_dataset")
        self.plainTextEdit_index = QtWidgets.QPlainTextEdit(Sensitivity)
        self.plainTextEdit_index.setGeometry(QtCore.QRect(10, 275, 111, 28))
        self.plainTextEdit_index.setToolTip("")
        self.plainTextEdit_index.setObjectName("plainTextEdit_index")
        self.comboBox_exp_no = QtWidgets.QComboBox(Sensitivity)
        self.comboBox_exp_no.setGeometry(QtCore.QRect(510, 40, 86, 25))
        self.comboBox_exp_no.setObjectName("comboBox_exp_no")
        self.pushButton_newExperiment = QtWidgets.QPushButton(Sensitivity)
        self.pushButton_newExperiment.setGeometry(QtCore.QRect(620, 40, 89, 25))
        self.pushButton_newExperiment.setObjectName("pushButton_newExperiment")
        self.gridLayoutWidget = QtWidgets.QWidget(Sensitivity)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 90, 111, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit_vd = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit_vd.setMinimumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vd.setMaximumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vd.setObjectName("plainTextEdit_vd")
        self.gridLayout.addWidget(self.plainTextEdit_vd, 1, 0, 1, 1)
        self.plainTextEdit_vi = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit_vi.setMinimumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vi.setMaximumSize(QtCore.QSize(50, 30))
        self.plainTextEdit_vi.setObjectName("plainTextEdit_vi")
        self.gridLayout.addWidget(self.plainTextEdit_vi, 1, 1, 1, 1)
        self.label_vd = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vd.setObjectName("label_vd")
        self.gridLayout.addWidget(self.label_vd, 0, 0, 1, 1)
        self.label_vi = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vi.setObjectName("label_vi")
        self.gridLayout.addWidget(self.label_vi, 0, 1, 1, 1)
        self.comboBox_nuctype = QtWidgets.QComboBox(Sensitivity)
        self.comboBox_nuctype.setGeometry(QtCore.QRect(710, 40, 86, 25))
        self.comboBox_nuctype.setObjectName("comboBox_nuctype")

        self.retranslateUi(Sensitivity)
        QtCore.QMetaObject.connectSlotsByName(Sensitivity)

    def retranslateUi(self, Sensitivity):
        _translate = QtCore.QCoreApplication.translate
        Sensitivity.setWindowTitle(_translate("Sensitivity", "Form"))
        self.checkBox_normalize.setStatusTip(_translate("Sensitivity", "Normalize sensitivities"))
        self.checkBox_normalize.setText(_translate("Sensitivity", "Normalize"))
        self.comboBox_sel_dataset.setStatusTip(_translate("Sensitivity", "Select sensitivity dataset"))
        self.plainTextEdit_index.setStatusTip(_translate("Sensitivity", "select indices for sensitivity (e.g. \"4\", \"3-8\" ...)"))
        self.comboBox_exp_no.setStatusTip(_translate("Sensitivity", "select experiment with number ..."))
        self.pushButton_newExperiment.setStatusTip(_translate("Sensitivity", "Add a new experiment"))
        self.pushButton_newExperiment.setText(_translate("Sensitivity", "New Exp."))
        self.label_vd.setText(_translate("Sensitivity", "vd"))
        self.label_vi.setText(_translate("Sensitivity", "vi"))
